--student id: 30653770
--student name: James Andrew Ure

-- Generated by Oracle SQL Developer Data Modeler 19.2.0.182.1216
--   at:        2020-05-12 11:46:20 AEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g

set echo on
SPOOL mau_schema_output.txt

DROP TABLE art CASCADE CONSTRAINTS;

DROP TABLE artist CASCADE CONSTRAINTS;

DROP TABLE customer CASCADE CONSTRAINTS;

DROP TABLE exhibition CASCADE CONSTRAINTS;

DROP TABLE gallery CASCADE CONSTRAINTS;

DROP TABLE sale CASCADE CONSTRAINTS;

DROP TABLE status CASCADE CONSTRAINTS;

DROP TABLE style CASCADE CONSTRAINTS;

CREATE TABLE art (
    art_no           NUMBER(7) NOT NULL,
    artist_code      NUMBER(7) NOT NULL,
    art_title        CHAR(3) NOT NULL,
    date_added       DATE NOT NULL,
    min_price        NUMBER(10, 2),
    media_desc       VARCHAR2(150),
    assigned_style   VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN art.art_no IS
    'Art number for each artist, primary key';

COMMENT ON COLUMN art.artist_code IS
    'Primary key of the artist (identifier)';

COMMENT ON COLUMN art.art_title IS
    'Title of the artwork';

COMMENT ON COLUMN art.date_added IS
    'Date the artwork was accepted into the MAU';

COMMENT ON COLUMN art.min_price IS
    'Minimum price of the artwork';

COMMENT ON COLUMN art.media_desc IS
    'Media description of the artwork';

COMMENT ON COLUMN art.assigned_style IS
    'Style to be assigned to the artwork - Primary key';

ALTER TABLE art ADD CONSTRAINT art_pk PRIMARY KEY ( art_no,
                                                    artist_code );

CREATE TABLE artist (
    artist_code       NUMBER(7) NOT NULL,
    artist_name       VARCHAR2(50) NOT NULL,
    contact_address   VARCHAR2(80) NOT NULL,
    artist_phone      CHAR(10) NOT NULL,
    stock_on_hand     NUMBER(4) NOT NULL
);

COMMENT ON COLUMN artist.artist_code IS
    'Primary key of the artist (identifier)';

COMMENT ON COLUMN artist.artist_name IS
    'name of the artist';

COMMENT ON COLUMN artist.contact_address IS
    'address to contact artist';

COMMENT ON COLUMN artist.artist_phone IS
    'phone number of artist';

COMMENT ON COLUMN artist.stock_on_hand IS
    'number of art stock artist has';

ALTER TABLE artist ADD CONSTRAINT artist_pk PRIMARY KEY ( artist_code );

CREATE TABLE customer (
    cust_id         NUMBER(7) NOT NULL,
    cust_name       VARCHAR2(50) NOT NULL,
    cust_address    VARCHAR2(80) NOT NULL,
    cust_phone      CHAR(10) NOT NULL,
    business_name   VARCHAR2(50)
);

COMMENT ON COLUMN customer.cust_id IS
    'Primary key of the customer';

COMMENT ON COLUMN customer.cust_name IS
    'Name of the customer';

COMMENT ON COLUMN customer.cust_address IS
    'address of the customer';

COMMENT ON COLUMN customer.cust_phone IS
    'contact phone number of customer';

COMMENT ON COLUMN customer.business_name IS
    'business name of the customer';

ALTER TABLE customer ADD CONSTRAINT customer_pk PRIMARY KEY ( cust_id );

CREATE TABLE exhibition (
    exhibition_id    NUMBER(7) NOT NULL,
    artist_code      NUMBER(7) NOT NULL,
    art_no           NUMBER(7) NOT NULL,
    gallery_id       NUMBER(7) NOT NULL,
    date_exh_start   DATE NOT NULL,
    date_exh_end     DATE NOT NULL
);

COMMENT ON COLUMN exhibition.exhibition_id IS
    'Surrogate key';

COMMENT ON COLUMN exhibition.artist_code IS
    'Primary key of the artist (identifier)';

COMMENT ON COLUMN exhibition.art_no IS
    'Art number for each artist, primary key';

COMMENT ON COLUMN exhibition.gallery_id IS
    'Primary key of the gallery';

COMMENT ON COLUMN exhibition.date_exh_start IS
    'The date the exhibition started';

COMMENT ON COLUMN exhibition.date_exh_end IS
    'When the exhibition will end';

CREATE UNIQUE INDEX exhibition__idx ON
    exhibition (
        art_no
    ASC,
        artist_code
    ASC );

ALTER TABLE exhibition ADD CONSTRAINT exhibition_pk PRIMARY KEY ( exhibition_id )
;

ALTER TABLE exhibition
    ADD CONSTRAINT exh_newkey UNIQUE ( art_no,
                                       artist_code,
                                       gallery_id );

CREATE TABLE gallery (
    gallery_id        NUMBER(7) NOT NULL,
    gallery_name      VARCHAR2(50) NOT NULL,
    manager_name      VARCHAR2(50) NOT NULL,
    gallery_str_num   NUMBER(4) NOT NULL,
    gallery_street    VARCHAR2(30) NOT NULL,
    gallery_town      VARCHAR2(30) NOT NULL,
    gallery_state     VARCHAR2(30) NOT NULL,
    gallery_phone     CHAR(10) NOT NULL,
    commission        NUMBER(3, 2) NOT NULL,
    gallery_open      CHAR(5),
    gallery_closes    CHAR(5)
);

COMMENT ON COLUMN gallery.gallery_id IS
    'Primary key of the gallery';

COMMENT ON COLUMN gallery.gallery_name IS
    'name of the gallery';

COMMENT ON COLUMN gallery.manager_name IS
    'name of the manager';

COMMENT ON COLUMN gallery.gallery_str_num IS
    'street number of the gallery';

COMMENT ON COLUMN gallery.gallery_street IS
    'street name of the gallery';

COMMENT ON COLUMN gallery.gallery_town IS
    'town name of the gallery';

COMMENT ON COLUMN gallery.gallery_state IS
    'state name of the gallery';

COMMENT ON COLUMN gallery.gallery_phone IS
    'phone number of the gallery';

COMMENT ON COLUMN gallery.commission IS
    'gallery''s commission when selling art';

COMMENT ON COLUMN gallery.gallery_open IS
    'time the gallery opens';

COMMENT ON COLUMN gallery.gallery_closes IS
    'time the gallery closes';

ALTER TABLE gallery ADD CONSTRAINT gallery_pk PRIMARY KEY ( gallery_id );

CREATE TABLE sale (
    sale_id         NUMBER(7) NOT NULL,
    sale_date       DATE,
    sale_price      NUMBER(10, 2),
    exhibition_id   NUMBER(7) NOT NULL,
    cust_id         NUMBER(7) NOT NULL
);

COMMENT ON COLUMN sale.sale_id IS
    'Primary key of the sale';

COMMENT ON COLUMN sale.sale_date IS
    'Date of sale';

COMMENT ON COLUMN sale.sale_price IS
    'Price the artwork was sold for';

COMMENT ON COLUMN sale.exhibition_id IS
    'Surrogate key';

COMMENT ON COLUMN sale.cust_id IS
    'Primary key of the customer';

CREATE UNIQUE INDEX sale__idx ON
    sale (
        exhibition_id
    ASC );

ALTER TABLE sale ADD CONSTRAINT sale_pk PRIMARY KEY ( sale_id );

CREATE TABLE status (
    "date"        DATE NOT NULL,
    art_status    VARCHAR2(150) NOT NULL,
    art_no        NUMBER(7) NOT NULL,
    artist_code   NUMBER(7) NOT NULL,
    gallery_id    NUMBER(7)
);

COMMENT ON COLUMN status."date" IS
    'Natural key - date the status was issued';

COMMENT ON COLUMN status.art_status IS
    'Natural key - status description of the art';

COMMENT ON COLUMN status.art_no IS
    'Art number for each artist, primary key';

COMMENT ON COLUMN status.artist_code IS
    'Primary key of the artist (identifier)';

COMMENT ON COLUMN status.gallery_id IS
    'Primary key of the gallery';

ALTER TABLE status
    ADD CONSTRAINT status_pk PRIMARY KEY ( art_status,
                                           "date",
                                           art_no,
                                           artist_code );

CREATE TABLE style (
    assigned_style   VARCHAR2(30) NOT NULL,
    parent_style     VARCHAR2(30) NOT NULL
);

COMMENT ON COLUMN style.assigned_style IS
    'Style to be assigned to the artwork - Primary key';

COMMENT ON COLUMN style.parent_style IS
    'Style to be assigned to the artwork - Primary key';

ALTER TABLE style ADD CONSTRAINT style_pk PRIMARY KEY ( assigned_style );

ALTER TABLE status
    ADD CONSTRAINT art_status FOREIGN KEY ( art_no,
                                            artist_code )
        REFERENCES art ( art_no,
                         artist_code );

ALTER TABLE art
    ADD CONSTRAINT art_style FOREIGN KEY ( assigned_style )
        REFERENCES style ( assigned_style );

ALTER TABLE art
    ADD CONSTRAINT artist_art FOREIGN KEY ( artist_code )
        REFERENCES artist ( artist_code );

ALTER TABLE style
    ADD CONSTRAINT child_parent_style FOREIGN KEY ( parent_style )
        REFERENCES style ( assigned_style );

ALTER TABLE sale
    ADD CONSTRAINT customer_sale FOREIGN KEY ( cust_id )
        REFERENCES customer ( cust_id );

ALTER TABLE exhibition
    ADD CONSTRAINT exhibition_art FOREIGN KEY ( art_no,
                                                artist_code )
        REFERENCES art ( art_no,
                         artist_code );

ALTER TABLE sale
    ADD CONSTRAINT exhibition_sale FOREIGN KEY ( exhibition_id )
        REFERENCES exhibition ( exhibition_id );

ALTER TABLE exhibition
    ADD CONSTRAINT gallery_exhibition FOREIGN KEY ( gallery_id )
        REFERENCES gallery ( gallery_id );

ALTER TABLE status
    ADD CONSTRAINT gallery_status FOREIGN KEY ( gallery_id )
        REFERENCES gallery ( gallery_id );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             8
-- CREATE INDEX                             2
-- ALTER TABLE                             18
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0

SPOOL off
set echo off
